CREATE TABLE Felhasznalo (
    Felhasznalo_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Felhasznalo_nev VARCHAR2(50) NOT NULL UNIQUE,
    Felhasznalo_email VARCHAR2(50) NOT NULL UNIQUE,
    Felhasznalo_jelszo VARCHAR2(50) NOT NULL,
    Oneletrajz_URL VARCHAR2(50) NOT NULL,
    Szul_datum TIMESTAMP NOT NULL,
    PRIMARY KEY(Felhasznalo_ID)
);
CREATE TABLE Ceg (
    Ceg_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Ceg_nev VARCHAR2(50) NOT NULL,
    PRIMARY KEY(Ceg_ID)
);
CREATE TABLE Allasok (
    Allas_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Allas_nev VARCHAR2(50) NOT NULL,
    Ervenyessegi_ido TIMESTAMP NOT NULL,
    PRIMARY KEY(Allas_ID)
);
CREATE TABLE Varosok (
    Varos_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Varosnev VARCHAR2(50) NOT NULL,
    Iranyitoszam NUMBER NOT NULL,
    PRIMARY KEY(Varos_ID)
);
CREATE TABLE Kovetelmenyek (
    Kov_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Kov_nev VARCHAR2(50) NOT NULL,
    PRIMARY KEY(Kov_ID)
);
CREATE TABLE AllasTipus (
    Tipus_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    Tipus_nev VARCHAR2(50) NOT NULL,
    PRIMARY KEY(Tipus_ID)
);
CREATE TABLE Lakik (
    Felhasznalo_ID NUMBER NOT NULL,
    Varos_ID NUMBER NOT NULL,
    CONSTRAINT Felhasznalo_Varos_fk FOREIGN KEY (Felhasznalo_ID) REFERENCES Felhasznalo(Felhasznalo_ID),
    CONSTRAINT Varos_Felhasznalo_fk FOREIGN KEY (Varos_ID) REFERENCES Varosok(Varos_ID)
);
CREATE TABLE Elofordul (
    Allas_ID NUMBER NOT NULL,
    Varos_ID NUMBER NOT NULL,
    CONSTRAINT Allas_Varos_fk FOREIGN KEY (Allas_ID) REFERENCES Allasok(Allas_ID),
    CONSTRAINT Varos_Allas_fk FOREIGN KEY (Varos_ID) REFERENCES Varosok(Varos_ID)
);
CREATE TABLE Feltetele (
    Allas_ID NUMBER NOT NULL,
    Kov_ID NUMBER NOT NULL,
    CONSTRAINT Allas_Kovetelmenyek_fk FOREIGN KEY (Allas_ID) REFERENCES Allasok(Allas_ID),
    CONSTRAINT Kovetelmenyek_Allas_fk FOREIGN KEY (Kov_ID) REFERENCES Kovetelmenyek(Kov_ID)
);
CREATE TABLE VanTipus (
    Allas_ID NUMBER NOT NULL,
    Tipus_ID NUMBER NOT NULL,
    CONSTRAINT Allas_Tipus_fk FOREIGN KEY (Allas_ID) REFERENCES Allasok(Allas_ID),
    CONSTRAINT Tipus_Allas_fk FOREIGN KEY (Tipus_ID) REFERENCES AllasTipus(Tipus_ID)
);
CREATE TABLE Meghirdet (
    Allas_ID NUMBER NOT NULL,
    Ceg_ID NUMBER NOT NULL,
    CONSTRAINT Allas_Ceg_fk FOREIGN KEY (Allas_ID) REFERENCES Allasok(Allas_ID),
    CONSTRAINT Ceg_Allas_fk FOREIGN KEY (Ceg_ID) REFERENCES Ceg(Ceg_ID)
)
