INSERT INTO VAROSOK(VAROSNEV) VALUES ('Izsák');
INSERT INTO VAROSOK(VAROSNEV) VALUES ('Szeged');
INSERT INTO VAROSOK(VAROSNEV) VALUES ('Kecskemét');
INSERT INTO VAROSOK(VAROSNEV) VALUES ('Budapest');

INSERT INTO ALLASTIPUS(TIPUS_NEV) VALUES ('Informatikai');
INSERT INTO ALLASTIPUS(TIPUS_NEV) VALUES ('Irodai');
INSERT INTO ALLASTIPUS(TIPUS_NEV) VALUES ('Építészeti');
INSERT INTO ALLASTIPUS(TIPUS_NEV) VALUES ('Mezőgazdasági');

INSERT INTO KOVETELMENYEK(KOV_NEV) VALUES ('Általános');
INSERT INTO KOVETELMENYEK(KOV_NEV) VALUES ('Középiskola');
INSERT INTO KOVETELMENYEK(KOV_NEV) VALUES ('Egyetem');
INSERT INTO KOVETELMENYEK(KOV_NEV) VALUES ('Nyelvvizsga');